apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  selector:
    app: cockroachdb
  ports:
    - port: 26257
      targetPort: 26257
  type: LoadBalancer
