---
apiVersion: v1
kind: Service
metadata:
  name: test-frr
spec:
  selector:
        app: hello-node
  ports:
        - port: 80
          protocol: TCP
          targetPort: 9376
  type: LoadBalancer
